### ISSUE TITLE
/inscription no té en compte si les places estan completes

### ISSUE THREAD

**Issue by sergiaguilar** [ahuangfeng/IntegrApp_BackEnd#13]
Ara mateix guardem les persones registrades a l'anunci en un camp del objecte anunci. Podríem guardar un nou camp amb persones acceptades, per així no tenir que recórrer les inscripcions cada cop que vulguem comprobar si ja hem omplert les places màximes de l'anunci. 

Ja que al camp Registered de Advert, tan sols guardem l'ID de les persones que han sol·licitat inscriure's a l'anunci. No guardem ni si han estat acceptades o no. Això ho guardem a inscriptions.

Com ho veieu?

**Comment by ahuangfeng** [comment]
a classe hem parlat de que al array registered, portarà l'objecte {userId: id, status: status, username:name} Així desde front podran accedir als usernames

**Comment by ahuangfeng** [comment]
nova implementació
