### ISSUE TITLE
New endpoint rating Forum

### ISSUE THREAD

**Issue by LBrull** [ahuangfeng/IntegrApp_BackEnd#18]
@sergiaguilar necessitem poder fer un POST o un PUT des de front i enviar la puntuació d'un user sobre un forum. A back s'hauria d'acumular sobre la puntuació que hi hagi i fer-li la nova mitjana, que seria puntuacio_acumulada/2. No crec que calgui vigilar si l'user ha puntuat ja o no, pero com vulgeu.
Merciiiiiiiiiiiiii jjajajaja :)

**Comment by sergiaguilar** [comment]
Valee! Aquest finde m'hi poso. No obstant la puntuació mitjana no podem anar-la calculant puntuacio_acumulada/2 perque sino perd valor la puntuació ja existent. Miraré la manera ideal de calcularla.
Merci @LBrull

**Comment by sergiaguilar** [comment]
Fet!
