### ISSUE TITLE
Bug found for #PUT inscription/id

### ISSUE THREAD

**Issue by manelalexg** [ahuangfeng/IntegrApp_BackEnd#23]
Bad Request in that endpoint, concretely throws the message "Cannot read property 'length' of null" when submitting a call with correct params.

curl -X PUT "https://integrappbackend.herokuapp.com/api/inscription/5afe8f8a4d014700148f355a" -H "accept: application/json" -H "x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI1YWVkZGRhOGI0ZDE5ODAwMTQyNDBhODMiLCJ1c2VybmFtZSI6Im1hbmVsYWxleGciLCJpYXQiOjE1MjY5ODAwNzJ9.qMyr5jTICMLvWA3VoNjWasypy9STzf1YYaXLkldnjVk" -H "Content-Type: application/json" -d "{ \"userId\": \"5afe8f494d014700148f3558\", \"status\": \"refused\"}"

**Comment by sergiaguilar** [comment]
Bug Fixed
