### ISSUE TITLE
POST /advert

### ISSUE THREAD

**Issue by ahuangfeng** [ahuangfeng/IntegrApp_BackEnd#6]
No pasan todos los tests:
El test que no pasa es el que tiene una fecha anterior a hoy

para reproducir error:
```
curl -X POST "http://localhost:8080/api/advert" -H  "accept: application/json" -H  "x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI1YWI4MmU0Y2Y5YmYyNjI1MzcyYmJhNTUiLCJ1c2VybmFtZSI6ImFodWFuZ2ZlbmciLCJpYXQiOjE1MjMzMDI1NTksImV4cCI6MTUyMzM4ODk1OX0.RbJ0pUoDjwU-tOBsunhd_vpuyt5VhuW7J8M8BetyEpg" -H  "Content-Type: application/json" -d "{  \"date\": \"05-01-2018 13:20\",  \"title\": \"Title\",  \"description\": \"description\",  \"places\": 3,  \"typeAdvert\": \"lookFor\"}"
```

**Comment by sergiaguilar** [comment]
Porque para crear un anuncio, la fecha del anuncio tiene que ser posterior a la fecha en que se crea.

**Comment by ahuangfeng** [comment]
No, no, xD, node me devuelve un status 200 con el advert creado.
Estoy enviando un advert para "05-01-2018 13:20" y considera que es correcto

**Comment by sergiaguilar** [comment]
Problem solved! Commit: Date format modified
