### ISSUE TITLE
PUT /user no funciona si posem un username no vàlid

### ISSUE THREAD

**Issue by ahuangfeng** [ahuangfeng/IntegrApp_BackEnd#9]
PUT /api/user, si li enviem aixo:
```
{
        "username": "",
        "password": "xxxxxxx",
        "type": "voluntary",
        "CIF": "string",
        "name": "nomProva",
        "email": "aa@gmail.com"
}
```
Funciona perfectament i no hauria
Lo mateix amb password i name

Executa els test amb `npm test` per veure lo que envio

**Comment by sergiaguilar** [comment]
Vale! Ara m'ho miro!!!! O sigui també haig de tenir en compte que el string no sigui un string buit no?

**Comment by ahuangfeng** [comment]
Sisi, en principi amb aixo ja passa.

**Comment by sergiaguilar** [comment]
La cosa es que si li pases un camp a modificar, pero el camp es un String buit, detecta que es un string buit i no ho modifica. Pero com faig la comprobació camp a camp, no retorna error. Sino que en comptes de modificar ho retorna igual.

**Comment by sergiaguilar** [comment]
Potser desde front ens envien:
{
        "username": "",
        "password": "xxxxxxx",
        "type": "",
        "CIF": "",
        "name": "nomProva",
        "email": ""
}

Ja que l'usuari només vol modificar el seu nom. Back-end l'unic camp que modifiquem es nom. Tota la resta ho mantindrà igual.

PD: He modificat lo de CIF, que abans no comprobava si era association o no.

**Comment by sergiaguilar** [comment]
Ara comprobo si es association. Si no es association CIF será un String buit. En canvi si es association s'afegirà el CIF corresponent..
